on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry install

    - name: Build Qt Files
      run: |
        poetry shell
        ./build-qt.sh
    - name: Build with PyInstaller
      run: |
        poetry shell
        ./make.sh

    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
